In [5]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')

In [6]:
car_data=pd.read_csv('audi.csv')
print(car_data)

      model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...    ...          ...      ...      ...  ...   ...         ...
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020  17199       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 9 columns]


## Manual EDA

In [7]:
# Number of records
print(len(car_data))

10668


In [8]:
# Number of records- Shape
print(car_data.shape)

(10668, 9)


In [9]:
# Checking the datatype of each column
print(car_data.dtypes)

model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object


In [10]:
# Checking null values
print(car_data.isna().sum())

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64


In [11]:
# Dataset information
print(car_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10668 entries, 0 to 10667
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         10668 non-null  object 
 1   year          10668 non-null  int64  
 2   price         10668 non-null  int64  
 3   transmission  10668 non-null  object 
 4   mileage       10668 non-null  int64  
 5   fuelType      10668 non-null  object 
 6   tax           10668 non-null  int64  
 7   mpg           10668 non-null  float64
 8   engineSize    10668 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 750.2+ KB
None


In [12]:
# Dataset details of numeric columns
display(car_data.describe())

year          price        mileage           tax           mpg  \
count  10668.000000   10668.000000   10668.000000  10668.000000  10668.000000   
mean    2017.100675   22896.685039   24827.244001    126.011436     50.770022   
std        2.167494   11714.841888   23505.257205     67.170294     12.949782   
min     1997.000000    1490.000000       1.000000      0.000000     18.900000   
25%     2016.000000   15130.750000    5968.750000    125.000000     40.900000   
50%     2017.000000   20200.000000   19000.000000    145.000000     49.600000   
75%     2019.000000   27990.000000   36464.500000    145.000000     58.900000   
max     2020.000000  145000.000000  323000.000000    580.000000    188.300000   

         engineSize  
count  10668.000000  
mean       1.930709  
std        0.602957  
min        0.000000  
25%        1.500000  
50%        2.000000  
75%        2.000000  
max        6.300000

In [13]:
# Create x
x=car_data.iloc[:,[0,1,3,4,5,6,7,8]].values
print(x.shape)
print(x)

(10668, 8)
[[' A1' 2017 'Manual' ... 150 55.4 1.4]
 [' A6' 2016 'Automatic' ... 20 64.2 2.0]
 [' A1' 2016 'Manual' ... 30 55.4 1.4]
 ...
 [' A3' 2020 'Manual' ... 150 49.6 1.0]
 [' Q3' 2017 'Automatic' ... 150 47.9 1.4]
 [' Q3' 2016 'Manual' ... 150 47.9 1.4]]


In [14]:
# Create y
y=car_data.iloc[:,[2]].values
print(y.shape)
print(y)

(10668, 1)
[[12500]
 [16500]
 [11000]
 ...
 [17199]
 [19499]
 [15999]]


In [15]:
# Display Top 5 - X variable 
display(pd.DataFrame(x).head())

0     1          2      3       4    5     6    7
0   A1  2017     Manual  15735  Petrol  150  55.4  1.4
1   A6  2016  Automatic  36203  Diesel   20  64.2  2.0
2   A1  2016     Manual  29946  Petrol   30  55.4  1.4
3   A4  2017  Automatic  25952  Diesel  145  67.3  2.0
4   A3  2019     Manual   1998  Petrol  145  49.6  1.0

## Label Encoding To Columns- model and fuel type

In [16]:
from sklearn.preprocessing import LabelEncoder
l1=LabelEncoder()
x[:,0]=l1.fit_transform(x[:,0])
l2=LabelEncoder()
x[:,4]=l2.fit_transform(x[:,4])
display(pd.DataFrame(x))

0     1          2      3  4    5     6    7
0      0  2017     Manual  15735  2  150  55.4  1.4
1      5  2016  Automatic  36203  0   20  64.2  2.0
2      0  2016     Manual  29946  2   30  55.4  1.4
3      3  2017  Automatic  25952  0  145  67.3  2.0
4      2  2019     Manual   1998  2  145  49.6  1.0
...   ..   ...        ...    ... ..  ...   ...  ...
10663  2  2020     Manual   4018  2  145  49.6  1.0
10664  2  2020     Manual   1978  2  150  49.6  1.0
10665  2  2020     Manual    609  2  150  49.6  1.0
10666  9  2017  Automatic   8646  2  150  47.9  1.4
10667  9  2016     Manual  11855  2  150  47.9  1.4

[10668 rows x 8 columns]

## One Hot Encoding To Column- transmission


In [17]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[2])],remainder='passthrough')
x = ct.fit_transform(x)
display (x.shape)
display (pd.DataFrame(x))

(10668, 10)

0    1    2  3     4      5  6    7     8    9
0      0.0  1.0  0.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  0.0  5  2016  36203  0   20  64.2  2.0
2      0.0  1.0  0.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  0.0  3  2017  25952  0  145  67.3  2.0
4      0.0  1.0  0.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  0.0  1.0  0.0  2  2020   4018  2  145  49.6  1.0
10664  0.0  1.0  0.0  2  2020   1978  2  150  49.6  1.0
10665  0.0  1.0  0.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  0.0  1.0  0.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 10 columns]

## Features Scaling – Standardization 

In [18]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
display(pd.DataFrame(x))

0         1         2         3         4         5         6  \
0     -0.583268  1.200728 -0.712333 -1.123544 -0.046450 -0.386836  1.050783   
1      1.714479 -0.832828 -0.712333 -0.160831 -0.507834  0.483989 -0.954181   
2     -0.583268  1.200728 -0.712333 -1.123544 -0.507834  0.217781  1.050783   
3      1.714479 -0.832828 -0.712333 -0.545916 -0.046450  0.047853 -0.954181   
4     -0.583268  1.200728 -0.712333 -0.738459  0.876318 -0.971285  1.050783   
...         ...       ...       ...       ...       ...       ...       ...   
10663 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.885343  1.050783   
10664 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.972136  1.050783   
10665 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -1.030381  1.050783   
10666  1.714479 -0.832828 -0.712333  0.609339 -0.046450 -0.688442  1.050783   
10667 -0.583268  1.200728 -0.712333  0.609339 -0.507834 -0.551913  1.050783   

              7         8         9  
0      0.357147  0.357550 -0.880218  
1     -1.578323  1.037130  0.114925  
2     -1.429440  0.357550 -0.880218  
3      0.282706  1.276528  0.114925  
4      0.282706 -0.090355 -1.543647  
...         ...       ...       ...  
10663  0.282706 -0.090355 -1.543647  
10664  0.357147 -0.090355 -1.543647  
10665  0.357147 -0.090355 -1.543647  
10666  0.357147 -0.221637 -0.880218  
10667  0.357147 -0.221637 -0.880218  

[10668 rows x 10 columns]

## Train Test Split 

In [19]:
from sklearn.model_selection import train_test_split
(x_train,x_test,y_train,y_test)=train_test_split(x,y,test_size=0.2,random_state=0)
print(x.shape,y.shape)
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(10668, 10) (10668, 1)
(8534, 10) (8534, 1)
(2134, 10) (2134, 1)


## Create Random Forest Regressor

In [20]:
from sklearn.ensemble import RandomForestRegressor
rf=RandomForestRegressor()
rf.fit(x_train,y_train)
display(rf)

RandomForestRegressor()

## Prediction with test data

In [21]:
y_pred=rf.predict(x_test)
display(y_pred)

array([14304.04, 23906.87, 27433.83, ..., 46399.8 , 31118.71,  9803.89])

## Display actual and Predicted Values 

In [22]:
print (pd.concat ([pd.DataFrame(y_test.reshape(len(y_test),1),columns =['Car Price']), 
                   pd.DataFrame(y_pred.reshape(len(y_pred),1),columns =['Price Prediction'])],axis =1))

      Car Price  Price Prediction
0         14998          14304.04
1         21950          23906.87
2         28990          27433.83
3         25489          27236.62
4         30950          32413.05
...         ...               ...
2129      23700          39090.12
2130      18000          16529.99
2131      45995          46399.80
2132      30500          31118.71
2133       8400           9803.89

[2134 rows x 2 columns]


## Display – Accuracy and Mean Absolute Error 

In [23]:
from sklearn.metrics import r2_score,mean_absolute_error
print('Accuracy: ',r2_score(y_test,y_pred))
print('Mean_Absolute_Error: ',mean_absolute_error(y_test,y_pred))

Accuracy:  0.9561375386114995
Mean_Absolute_Error:  1528.820285781278


## Prediction with complete data

In [24]:
c_pred=rf.predict(x)
display(c_pred)

array([12864.1 , 16529.77, 11570.62, ..., 17949.1 , 20098.27, 18176.39])

## Display actual and Predicted Values

In [25]:
display(pd.concat ([car_data,pd.DataFrame(c_pred.reshape(len(c_pred),1),columns =['Price Prediction'])],axis =1))

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize  Price Prediction  
0             1.4          12864.10  
1             2.0          16529.77  
2             1.4          11570.62  
3             2.0          17902.98  
4             1.0          17033.78  
...           ...               ...  
10663         1.0          16898.13  
10664         1.0          17213.92  
10665         1.0          17949.10  
10666         1.4          20098.27  
10667         1.4          18176.39  

[10668 rows x 10 columns]

## Display – Accuracy and Mean Absolute Error

In [26]:
from sklearn.metrics import r2_score,mean_absolute_error
print('Accuracy: ',r2_score(y,c_pred))
print('Mean_Absolute_Error: ',mean_absolute_error(y,c_pred))

Accuracy:  0.9859239256643632
Mean_Absolute_Error:  781.2328247474646


## Create Linear Regression Model

In [27]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
display(lr)

LinearRegression()

## Prediction with test data

In [28]:
y_pred=lr.predict(x_test)
display(pd.DataFrame(y_pred))

0
0     13062.417648
1     29350.247388
2     31943.967808
3     26795.619718
4     31438.948683
...            ...
2129  41582.338659
2130  20715.033809
2131  42611.259923
2132  31515.735002
2133   7294.332756

[2134 rows x 1 columns]

## Display Actual and Predicted Values

In [29]:
print (pd.concat ([pd.DataFrame(y_test.reshape(len(y_test),1),columns =['Car Price']), 
                   pd.DataFrame(y_pred.reshape(len(y_pred),1),columns =['Price Prediction'])],axis =1))

      Car Price  Price Prediction
0         14998      13062.417648
1         21950      29350.247388
2         28990      31943.967808
3         25489      26795.619718
4         30950      31438.948683
...         ...               ...
2129      23700      41582.338659
2130      18000      20715.033809
2131      45995      42611.259923
2132      30500      31515.735002
2133       8400       7294.332756

[2134 rows x 2 columns]


## Display- Accuracy and Mean Absolute Error

In [30]:
from sklearn.metrics import r2_score,mean_absolute_error
print('Accuracy: ',r2_score(y_test,y_pred))
print('Mean_Absolute_Error: ',mean_absolute_error(y_test,y_pred))

Accuracy:  0.7916670925031881
Mean_Absolute_Error:  3381.9167483000706


## Prediction for complete dataset

In [31]:
c_pred=lr.predict(x)
display(c_pred)

array([[14629.83482405],
       [20670.90779921],
       [13810.01031988],
       ...,
       [19407.66134549],
       [21034.83116012],
       [16691.09313906]])

## Display Actual and Predicted values

In [32]:
display(pd.concat ([car_data,pd.DataFrame(c_pred.reshape(len(c_pred),1),columns =['Price Prediction'])],axis =1))

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize  Price Prediction  
0             1.4      14629.834824  
1             2.0      20670.907799  
2             1.4      13810.010320  
3             2.0      19949.798672  
4             1.0      17350.396723  
...           ...               ...  
10663         1.0      19190.495099  
10664         1.0      19277.571094  
10665         1.0      19407.661345  
10666         1.4      21034.831160  
10667         1.4      16691.093139  

[10668 rows x 10 columns]

## Display-Accuracy and Mean Absolute Error

In [33]:
from sklearn.metrics import r2_score,mean_absolute_error
print('Accuracy: ',r2_score(y,c_pred))
print('Mean_Absolute_Error: ',mean_absolute_error(y,c_pred))

Accuracy:  0.7907228785075128
Mean_Absolute_Error:  3344.6148563131032


## Create Model Extra Tree Regressor 

In [34]:
from sklearn.ensemble import  ExtraTreesRegressor
ET=ExtraTreesRegressor(n_estimators = 120)
ET.fit(x_train,y_train)
y_pred=ET.predict(x_test)
from sklearn.metrics import r2_score,mean_absolute_error
print  ('Accuracy: ', r2_score(y_test, y_pred))
print  ('Mean_Absolute_Error: ', mean_absolute_error(y_test,y_pred))

Accuracy:  0.9565727819637722
Mean_Absolute_Error:  1537.8415073414556


## Display the Result for Complete Dataset

In [35]:
c_pred = ET.predict(x)
display (c_pred)
result = pd.concat([car_data,pd.DataFrame(c_pred,columns = ['Price Prediction'])],axis=1)
display( result)

array([12500.        , 16500.        , 11000.        , ...,
       17199.        , 19499.        , 18035.66666667])

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize  Price Prediction  
0             1.4      12500.000000  
1             2.0      16500.000000  
2             1.4      11000.000000  
3             2.0      16800.000000  
4             1.0      17300.000000  
...           ...               ...  
10663         1.0      16999.000000  
10664         1.0      16999.000000  
10665         1.0      17199.000000  
10666         1.4      19499.000000  
10667         1.4      18035.666667  

[10668 rows x 10 columns]

## Display – Accuracy and Mean Absolute Error 

In [36]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('Accuracy: ', r2_score(y, c_pred))
print  ('Mean_Absolute_Error', mean_absolute_error(y,c_pred))

Accuracy:  0.990398443961703
Mean_Absolute_Error 350.40865350164563


## Install CatBoost

## Create Model CatBoostRegressor

In [37]:
from catboost import CatBoostRegressor
cat=CatBoostRegressor()
print(cat.fit(x_train,y_train))

Learning rate set to 0.057452
0:	learn: 11184.0694779	total: 113ms	remaining: 1m 52s
1:	learn: 10690.2138498	total: 118ms	remaining: 58.6s
2:	learn: 10221.1011877	total: 122ms	remaining: 40.7s
3:	learn: 9778.8067263	total: 128ms	remaining: 32s
4:	learn: 9382.6454054	total: 134ms	remaining: 26.7s
5:	learn: 8989.9290587	total: 138ms	remaining: 22.9s
6:	learn: 8628.4892653	total: 144ms	remaining: 20.5s
7:	learn: 8280.9179062	total: 149ms	remaining: 18.5s
8:	learn: 7950.5476053	total: 154ms	remaining: 17s
9:	learn: 7636.7735365	total: 159ms	remaining: 15.8s
10:	learn: 7349.6084699	total: 165ms	remaining: 14.8s
11:	learn: 7084.0457263	total: 169ms	remaining: 13.9s
12:	learn: 6842.7060927	total: 175ms	remaining: 13.3s
13:	learn: 6608.0244743	total: 182ms	remaining: 12.8s
14:	learn: 6387.7285726	total: 189ms	remaining: 12.4s
15:	learn: 6170.1354894	total: 195ms	remaining: 12s
16:	learn: 5973.9133066	total: 200ms	remaining: 11.6s
17:	learn: 5780.4713044	total: 206ms	remaining: 11.3s
18:	learn:

## Prediction with test data

In [38]:
cat_pred=cat.predict(x_test)
display(cat_pred)

array([13386.63817795, 24056.86842882, 28082.99514751, ...,
       45959.31234642, 31714.44751009,  9481.45994163])

## Display Actual and Predicted Values

In [39]:
print (pd.concat ([pd.DataFrame(y_test.reshape(len(y_test),1),columns =['Car Price']), 
                   pd.DataFrame(cat_pred.reshape(len(y_pred),1),columns =['Price Prediction'])],axis =1))

      Car Price  Price Prediction
0         14998      13386.638178
1         21950      24056.868429
2         28990      28082.995148
3         25489      26952.248348
4         30950      31515.043275
...         ...               ...
2129      23700      36642.235032
2130      18000      17075.243772
2131      45995      45959.312346
2132      30500      31714.447510
2133       8400       9481.459942

[2134 rows x 2 columns]


## Display-Accuracy and Mean Absolute Error

In [40]:
from sklearn.metrics import r2_score,mean_absolute_error
print('Accuracy: ',r2_score(y_test,cat_pred))
print('Mean_Absolute_Error: ',mean_absolute_error(y_test,cat_pred))

Accuracy:  0.9641612028134969
Mean_Absolute_Error:  1453.5230700749125


## Prediction with complete dataset

In [41]:
catc_pred=cat.predict(x)
display(catc_pred)

array([13989.8267214 , 16578.03846793, 12489.54800057, ...,
       18716.55396652, 20908.57305802, 17896.99245815])

## Display Actual and Predicted Values

In [42]:
result = pd.concat([car_data,pd.DataFrame(catc_pred ,columns = ['Price Prediction'])],axis=1)
display( result)

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize  Price Prediction  
0             1.4      13989.826721  
1             2.0      16578.038468  
2             1.4      12489.548001  
3             2.0      18793.884463  
4             1.0      18493.205301  
...           ...               ...  
10663         1.0      19428.713314  
10664         1.0      18877.541748  
10665         1.0      18716.553967  
10666         1.4      20908.573058  
10667         1.4      17896.992458  

[10668 rows x 10 columns]

## Display-Accuracy and Mean Absolute Error

In [43]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('Accuracy: ', r2_score(y, catc_pred))
print  ('Mean_Absolute_Error', mean_absolute_error(y,catc_pred))

Accuracy:  0.9745608180217411
Mean_Absolute_Error 1300.981301437808


## RandomizedSearchCV

In [44]:
# Hyperparameter Tuning and RandomizedSearchCV - Model used – RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start = 80, stop = 1500, num = 10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(6, 45, num = 5)]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10]

## create random grid

In [45]:
from sklearn.ensemble import RandomForestRegressor
rand_grid={'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

rf=RandomForestRegressor()

rCV=RandomizedSearchCV(estimator=rf,param_distributions=rand_grid,scoring='neg_mean_squared_error',n_iter=10,cv=5,random_state=42, n_jobs = -1)

## Fit Model

In [46]:
display(rCV.fit(x_train,y_train))

RandomizedSearchCV(cv=5, estimator=RandomForestRegressor(), n_jobs=-1,
                   param_distributions={'max_depth': [6, 15, 25, 35, 45],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [80, 237, 395, 553, 711,
                                                         868, 1026, 1184, 1342,
                                                         1500]},
                   random_state=42, scoring='neg_mean_squared_error')

## Prediction for test data

In [47]:
rf_pred=rCV.predict(x_test)
display (rf_pred)

array([14012.67793543, 23728.91599507, 28526.21411915, ...,
       48186.30668738, 31353.91754862, 10029.42141318])

## Display Mean Absolute Error and Mean Squared Error

In [48]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print('MAE: ',mean_absolute_error(y_test,rf_pred))
print('MSE: ',mean_squared_error(y_test,rf_pred))

MAE:  1502.945811628369
MSE:  5677062.598849226


## Display the Accuracy

In [49]:
from sklearn.metrics import r2_score
print('Accuracy: ',r2_score(y_test,rf_pred))

Accuracy:  0.9586870372131934


## Display the Result Complete the Data 

In [50]:
full_rf_pred=rCV.predict(x)
display (full_rf_pred)

array([13275.12126104, 16504.77980516, 11998.28516315, ...,
       18029.67270339, 20463.4705061 , 18516.93305717])

## Display Error and accuracy 

In [51]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print('MAE: ',mean_absolute_error(y,full_rf_pred))
print('MSE: ',mean_squared_error(y,full_rf_pred))
print('Accuracy: ',r2_score(y,full_rf_pred))

MAE:  1137.6244530006327
MSE:  3165337.7521811267
Accuracy:  0.9769331704445062


## Create Pickle File 

In [52]:
#Use pickle to save our model so that we can use it later
import pickle 
# Saving model to disk
pickle.dump(cat, open('model.pkl','wb'))

## Load Pickle File and  do Prediction  

In [53]:
model=pickle.load(open('model.pkl','rb'))
p_pred = model.predict (x)
print (p_pred)

[13989.8267214  16578.03846793 12489.54800057 ... 18716.55396652
 20908.57305802 17896.99245815]


## Display the result   

In [54]:
result = pd.concat([car_data,pd.DataFrame(p_pred ,columns = ['Price Prediction'])],axis=1)
display( result)

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize  Price Prediction  
0             1.4      13989.826721  
1             2.0      16578.038468  
2             1.4      12489.548001  
3             2.0      18793.884463  
4             1.0      18493.205301  
...           ...               ...  
10663         1.0      19428.713314  
10664         1.0      18877.541748  
10665         1.0      18716.553967  
10666         1.4      20908.573058  
10667         1.4      17896.992458  

[10668 rows x 10 columns]

## Display the Accuracy and Error   

In [55]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('Accuracy: ', r2_score(y, p_pred))
print  ('Mean_Absolute_Error: ', mean_absolute_error(y,p_pred))

Accuracy:  0.9745608180217411
Mean_Absolute_Error:  1300.981301437808
